### PR TITLE
Add poster image functionality

### PR DESCRIPTION
**Pull request by JeffTomlinson**
Adds functionality for MediaElement video poster images. 

Borrowed and tweaked some code from the [Video.js module](https://www.drupal.org/project/videojs) for this.

### CODE REVIEW

**Comment by ablank** [comment]
Thanks Jeff- I like it :) I'll test this weekend and merge as long as there aren't any conflicts.

**Comment by ablank** [comment]
Hi Jeff- I like the idea of having a poster image, but this commit breaks format settings for me (http response 500 - undefined AJAX error). I'll take a look at resolving if/when I have time, or if you can resolve I'll merge the feature.

**Comment by JeffTomlinson** [comment]
Hi @ablank, thanks for taking a look. I'd be happy to debug and fix but unfortunately I'm unable to reproduce the issue. If I understand correctly, you're getting the error on the node "Manage Display" tab. Can you provide any more details that might help me reproduce? What version of jQuery are you running?

Also, thanks for this module, it's one of the more workable Drupal video implementations I've tried.

**Comment by ablank** [comment]
Glad you like it :)

Correct, the issue is under manage display, when selecting the format settings ajax request returns 500. Tested on a fresh Drupal 7.39 install, Seven admin theme, core jQuery 1.4. Console isn't throwing errors, so I'm pretty sure the issue is php.

**Comment by JeffTomlinson** [comment]
Hmm. Still can't reproduce mirroring your config above. Bummer. `¯\_(ツ)_/¯`

PHP: 5.5.26

You don't have the issue on that environment using the 7.x-1.x branch?

I don't know...it's weird, I'm not getting any console or PHP errors either.

**Comment by ablank** [comment]
I've sorted the error - there was an added dependency on image :) I'd like to test a bit more and make a few changes (i.e. move the poster array to subset of appearance) but so far it looks good and I should be ready merge the feature in the next few days. 

Thanks for the contrib!

**Comment by JeffTomlinson** [comment]
Good news! Thanks for taking the time to debug.

**Comment by ablank** [comment]
I've tweaked things a bit- Love to get your input :)
- Poster option only displays if an image is available
- Poster available to Link & File content, as well as Audio & Video
- Moved settings to subset of appearance

**Comment by JeffTomlinson** [comment]
@ablank This is working great thanks!

**Pull request closed without merging**
